spring.datasource.url=${DB_URL:jdbc:h2:mem:banking;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.open-in-view=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8081